### ISSUE TITLE
InputLockManager behavior (AGX conflict)

### ISSUE THREAD

**Issue by SirDiazo** [zentarul/camerafocuschanger#1]
Alright, looking at your code, specifically this line:

https://github.com/zentarul/camerafocuschanger/blob/master/CameraFocusChanger/CameraFocusChanger.cs#L140

I have to ask what you are trying to accomplish with the InputLockManager check?

The reason I ask is that I don't think it is doing quite what you expect.

The InputLockManager class works on an enum variable and the ALL_SHIP_CONTROLS value is a combination value of the individual pieces of the vessel.

So when my AGX mod locks out CUSTOM_ACTION_GROUPS, which is part of the ALL_SHIP_CONTROLS collection, when the line of code I linked above query's InputLockManager.ALL_SHIP_CONTROLS, because CUSTOM_ACTION_GROUPS (and only that) is set, it still causes ALL_SHIP_CONTROLS to return true for locked even though only CUSTOM_ACTION_GROUPS is actually locked.

What are you actually trying to check with this line of code? Perhaps there's value I could point you towards that would work?

Regardless, I believe that it needs to be changed. As is stands, CFC will not work when:
-Stock Vessel is out of control (no kerbals and no probe core on board)
-Stock Vessel is in limited control (no kerbals onboard, probe core on board but no link to KSC)
-Stock Timewarp is engaged.
-AGX is installed.
-RemoteTech is installed (but only under certain conditions)
-Any other mod that applies a ControlLock.

**Comment by LittleCodeGeek** [comment]
Hi @SirDiazo, thanks for the heads up! The code in question is something that hvacengi from kOS gave me. I admit that I didn't look deep into what it was doing.

In any case, the goal of that line of code is to figure out if someone else has keyboard focus for a text input field, such as the Flag name and description or the kOS console or any other mod with a text field like MechJeb or whatever.

I'll look at the other values for that lock flag, but if you have a better idea of what to do, please let me know!
